-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 19:47:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Smmail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Smmail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Smmail` DEFAULT CHARACTER SET utf8 ;
USE `Smmail` ;

-- -----------------------------------------------------
-- Table `Smmail`.`SmmailContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smmail`.`SmmailContacts` (
  `ContactId` INT(21) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(120) NULL,
  `PhoneNumber` INT(20) NULL,
  PRIMARY KEY (`ContactId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smmail`.`SmmailGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smmail`.`SmmailGroups` (
  `GroupId` INT(21) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`GroupId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smmail`.`SmmailMessages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smmail`.`SmmailMessages` (
  `MessageId` INT(21) NOT NULL AUTO_INCREMENT,
  `GroupIdFk` INT(21) NOT NULL,
  `Message` TEXT NOT NULL,
  `TimeSent` TIMESTAMP NOT NULL,
  PRIMARY KEY (`MessageId`),
  INDEX `MessageGroupId_idx` (`GroupIdFk` ASC) VISIBLE,
  CONSTRAINT `MessageGroupId`
    FOREIGN KEY (`GroupIdFk`)
    REFERENCES `Smmail`.`SmmailGroups` (`GroupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smmail`.`SmmailGroupContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smmail`.`SmmailGroupContact` (
  `ContactIdFk` INT(21) NOT NULL,
  `GroupIdFk` INT(21) NOT NULL,
  `IsEmailGroup` TINYINT(1) NOT NULL,
  `IsSmsGroup` TINYINT(1) NOT NULL,
  INDEX `GCContactId_idx` (`ContactIdFk` ASC) VISIBLE,
  INDEX `GCGroupId_idx` (`GroupIdFk` ASC) VISIBLE,
  CONSTRAINT `GCContactId`
    FOREIGN KEY (`ContactIdFk`)
    REFERENCES `Smmail`.`SmmailContacts` (`ContactId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GCGroupId`
    FOREIGN KEY (`GroupIdFk`)
    REFERENCES `Smmail`.`SmmailGroups` (`GroupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smmail`.`SmmailMessageReceiveDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smmail`.`SmmailMessageReceiveDetails` (
  `ContactIdFk` INT(21) NOT NULL,
  `MessageIdFk` INT(21) NOT NULL,
  `IsSent` TINYINT(1) NOT NULL,
  `SentTime` TIMESTAMP NULL,
  INDEX `MRDContactId_idx` (`ContactIdFk` ASC) VISIBLE,
  INDEX `MRDMessageId_idx` (`MessageIdFk` ASC) VISIBLE,
  CONSTRAINT `MRDContactId`
    FOREIGN KEY (`ContactIdFk`)
    REFERENCES `Smmail`.`SmmailContacts` (`ContactId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MRDMessageId`
    FOREIGN KEY (`MessageIdFk`)
    REFERENCES `Smmail`.`SmmailMessages` (`MessageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
